# remote_theme: google/docsy@main
remote_theme: gohugo-theme-ananke@main
plugins:
- jekyll-remote-theme

title: Car logo Classification
description: An image classifiacation API that classifies 20 different types of cars logo around the world

aurhor:
  name: Mohammad Fayez Ullah